version: "3.9"
services:
  react-app:
    #stdin_open: true
    #dtty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=dima-prod
    env_file:
      - ./.env
